SELECT * FROM books;
SELECT * FROM branch;
SELECT * FROM employees;
SELECT * FROM issued_status;
SELECT * FROM return_status;
SELECT * FROM members;

-- Project Task

-- Q.1 Create a new member record in the members table with values ('C201', 'Evelina', '695 West St', '2023-01-15').

INSERT INTO members(member_id, member_name, member_address, reg_date)
VALUES
('C120', 'Evelina','695 West St','2023-02-15');


-- Q.2 Find all books whose rental_price is higher than the average rental_price of all books.

SELECT *
FROM book
WHERE rental_price > (
SELECT AVG(rental_price) FROM book
);


-- Q.3 Find all employees and show a single column employee_details in the format emp_id - emp_name - position - branch_id.

SELECT 
 CONCAT(emp_id, ' - ', emp_name, ' - ', position, ' - ',salary, ' - ', branch_id) AS employee_details
FROM employees;


-- Q.4 Find the top 5 members who issued the highest number of books.

SELECT
m.member_name,
m.member_id,
COUNT(ist.issued_id) AS total_issued
FROM members m
JOIN
issued_status ist
ON m.member_id = ist.issued_member_id
GROUP BY m.member_name, m.member_id
ORDER BY total_issued DESC LIMIT 5;


-- Q.5 Find branch-wise total issued books and total returned books.

SELECT 
e.branch_id, 
COUNT(ist.issued_id) as total_issued_books,
COUNT(r.return_id) as total_returned_books
FROM employees e
JOIN issued_status ist
ON e.emp_id = ist.issued_id
LEFT JOIN return_status r
ON ist.issued_id = r.issued_id
GROUP BY e.branch_id
ORDER BY e.branch_id;


-- Q.6 List all unique names from employees and members in a single column as person_name.

SELECT emp_name AS person_name
FROM employees
UNION
SELECT member_name AS person_name
FROM members;


-- Q.7 Find members who have issued more than 2 books using GROUP BY + HAVING.

SELECT issued_member_id,
COUNT(issued_id)
FROM issued_status
GROUP BY issued_member_id
HAVING COUNT(issued_id) >2;


-- Q.8 Retrieve All Books Issued After a Specific Date -- Objective: Select all books issued after '2024-01-01'.

SELECT * FROM issued_status
WHERE issued_date > '2024-01-01';


-- Q.9 Find branch-wise total employees and average salary using JOIN + GROUP BY.

SELECT b.branch_id,
COUNT(e.emp_id) AS total_employee,
AVG(e.salary)AS avg_salary
FROM branch b
JOIN
employees e
ON b.branch_id = e.branch_id
GROUP BY b.branch_id;

-- Q.10 Find the 5th highest rental_price from the book table.

SELECT rental_price
FROM books
ORDER BY rental_price DESC
LIMIT 1 OFFSET 4;

-- Q.11 Find the top 5 most issued books (isbn + book_title) with total issue count.

SELECT b.isbn,
b.book_title,
COUNT(*) AS total_issued
FROM issued_status ist
JOIN
books b
ON b.isbn = ist.issued_book_isbn
GROUP BY b.isbn, b.book_title
ORDER BY total_issued DESC
LIMIT 5;


-- Q.12 Find the second highest salary among employees.
SELECT
MAX(salary)
FROM employees
WHERE salary < (
  SELECT MAX(salary) FROM employees
);

-- Q.13 Show members who issued at least 1 book but never returned any book.

SELECT m.member_id,
m.member_name,
COUNT(ist.issued_id) AS total_issued
FROM members m
JOIN
issued_status ist
ON ist.issued_member_id = m.member_id
LEFT JOIN return_status rs
ON rs.issued_id = ist.issued_id
GROUP BY m.member_id,m.member_name
HAVING count(rs.return_id) = 0;


-- Q.14 Find the total rental income generated by each author from issued books.

SELECT 
    b.author,
    SUM(b.rental_price) AS total_rental_income
FROM issued_status ist
JOIN book b
ON ist.issued_book_isbn = b.isbn
GROUP BY b.author; 


-- Q.15 List employees whose salary is higher than their branch’s average salary using subquery.

SELECT
emp_id,
emp_name,
position,
salary,
branch_id
FROM employees
WHERE salary > (
      SELECT AVG(salary) FROM employees
	  WHERE branch_id = employees.branch_id
);


-- Q.16 Find all books that are currently issued and not yet returned, showing issued_id, issued_book_isbn, issued_book_name, and issued_date.

SELECT 
    ist.issued_id,
    ist.issued_book_isbn,
    ist.issued_book_name,
    ist.issued_date
FROM issued_status ist
LEFT JOIN return_status rs
ON ist.issued_id = rs.issued_id
WHERE rs.issued_id IS NULL;

 --
